name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  publish:
    # Run only when the ref is a tag (prevents accidental runs on branches)
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Lint, typecheck and test
        run: |
          npm run build
          npm run typecheck
          npm run lint
          npm run test:ci

      - name: Ensure tag matches package version
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          PKG_VERSION=$(node -p "require('./package.json').version")
          if [[ "$TAG" != "v$PKG_VERSION" ]]; then
            echo "Tag ($TAG) does not match package.json version (v$PKG_VERSION)" >&2
            exit 1
          fi

      - name: Publish (private)
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish
